# Generated by Django 4.1.7 on 2023-08-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0003_alter_agency_options"),
        ("accounts", "0002_user_agency_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(
                default="1",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agency.agency",
            ),
        ),
    ]
