# Generated by Django 4.1.7 on 2023-08-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mPactSessions", "0001_initial"),
        ("agency", "0003_alter_agency_options"),
        ("services", "0001_initial"),
        ("courses", "0002_course_agency"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="courses",
        ),
        migrations.AlterField(
            model_name="customer",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="agency.agency",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="courseClass",
            field=models.ManyToManyField(
                blank=True, null=True, to="courses.courseclass"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="services",
            field=models.ManyToManyField(blank=True, null=True, to="services.service"),
        ),
        migrations.RemoveField(
            model_name="customer",
            name="sessions",
        ),
        migrations.AddField(
            model_name="customer",
            name="sessions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mPactSessions.session",
            ),
        ),
    ]
