# Generated by Django 4.1.7 on 2023-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_service_agency"),
        ("courses", "0002_course_agency"),
        ("customers", "0002_remove_customer_courses_alter_customer_agency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="courseClass",
            field=models.ManyToManyField(blank=True, to="courses.courseclass"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="services",
            field=models.ManyToManyField(blank=True, to="services.service"),
        ),
    ]
