# Generated by Django 4.1.7 on 2023-08-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mPactSessions", "0002_session_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionoutcome",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sessionoutcome",
            name="outcome",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
