name: Format Code with Black

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install Black
        run: pip install black

      - name: Format with Black
        run: black .

      - name: Commit formatted code
        run: git add . && git diff --quiet || git commit -m "Apply Black formatting"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
